### PR TITLE
Fix `@year` slot recycling in `as.period(unit = "month")`

### LINKED ISSUE #1109: `as.period(<Interval>, unit = "month")` needs to recycle the `0` `year`
Seen here https://github.com/tidyverse/dplyr/issues/6789

``` r
library(lubridate)

x <- interval(
  start = as.Date("2019-01-01") + 0:2,
  end = as.Date("2023-01-02") + c(0, 100, 200),
  tz = "UTC"
)
x
#> [1] 2019-01-01 UTC--2023-01-02 UTC 2019-01-02 UTC--2023-04-12 UTC
#> [3] 2019-01-03 UTC--2023-07-21 UTC

y <- as.period(x, "months")
y
#> [1] "48m 1d 0H 0M 0S"  "51m 10d 0H 0M 0S" "54m 18d 0H 0M 0S"

# look at `year` - oh no!
unclass(y)
#> [1] 0 0 0
#> attr(,"year")
#> [1] 0
#> attr(,"month")
#> [1] 48 51 54
#> attr(,"day")
#> [1]  1 10 18
#> attr(,"hour")
#> [1] 0 0 0
#> attr(,"minute")
#> [1] 0 0 0

# makes these inconsistent
year(y)
#> [1] 0
month(y)
#> [1] 48 51 54
```

A large amount of things rely on the Period internals being recycled to the same length, so I think this is a bug (unlike where POSIXlt allows partially recycled elements, which is just a mess)

Seems relatively easy to fix by going through the `new()` Period constructor, which does recycling and `NA` standardization for us.

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #1109

### CODE REVIEW

File: R/coercion.r [hunk 1]
```diff
@@ -407,10 +407,8 @@ setMethod("as.period", signature(x = "Interval"), function(x, unit = NULL, ...)
   switch(unit,
     year = .int_to_period(x),
     month = {
-      pers <- .int_to_period(x)
-      month(pers) <- month(pers) + year(pers) * 12
-      year(pers) <- 0
-      pers
+      x <- .int_to_period(x)
+      as.period(x, unit = unit)
```
Comment (DavisVaughan) [inline R/coercion.r:411]: Standardized to just call `as.period()` to go through the Period method, since at this point the code paths are exactly the same. Hopefully this makes them less likely to get out of sync going forward

**Comment by vspinu** [comment]
Much better indeed. Thanks!
